services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3003'
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://mongodb:27017/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
